semaster=input("請輸入課程期數: ")
course=input("請輸入課程名稱: ")
name=input("請輸入姓名: ")
background=input("請輸入您的背景(科系或職業): ")
perpose=input("請簡述對於本課程得期望(列出幾點修完課程想得到的技能/對自己未來的規劃): ")

print("------------------------------------------")
print("第%s期 - %s "%(semaster,course))
print("姓名：",name)
print("==========================================")
print( name," 修習完課程[ ",course," ]後")
print("結業成果獲得: ",perpose)
print("well done")
print("------------------------------------------")
